### ISSUE TITLE
Sending integers above uint64 max size from trezorlib crashes on CBOR serialization

### ISSUE THREAD

**Issue by gabrielKerekes** [vacuumlabs/trezor-firmware#61]
When sending integers above uint64 max size (18446744073709551615) as part of input for transaction signing from trezorlib the integers aren't checked for validity (not even by protobuf) and are received in FW code without change. I.e. you send `ttl=18446744073709551616` and Trezor FW actually uses that value and this value is also shown to the user for confirmation. When it comes to CBOR serialization though, the FW will crash because CBOR can't (and probably shouldn't) handle numbers > uint64.

This can happen with `ttl`, token bundle token `amount`, catalyst registration `nonce` and other uint64 values which aren't checked for upper bounds in the FW.

Actionables:
Analyze the best way/place for validation/handling of integers larger than uint64 max size and implement.

**Comment by davidmisiak** [comment]
It seems like Trezor already fixed this globally, see https://github.com/vacuumlabs/trezor-firmware/blob/master/python/src/trezorlib/protobuf.py#L450-L462

Eg. trying to sign a tx with `ttl=18446744073709551616` throws
```
ValueError: Value 18446744073709551616 in field ttl does not fit into uint64
```

I tried this with Connect just to see what happens. Signing a tx with `ttl: "18446744073709551616"` is successful and Trezor gets `ttl=0`, which means that the value overflows.

I guess that it's okay this way (since the user sees the value; even though it would be a bit nicer if Connect threw an error), what do you think?

**Comment by gabrielKerekes** [comment]
Ah, ok, so this was probably just a trezorlib issue anyways. Thanks for checking it out. I don't see any validation happening anywhere in Connect regarding number size and it indeed should be safe, so let's not deal with that now.
